# Generated by Django 2.0 on 2018-08-16 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('isbn_number', models.CharField(max_length=13)),
            ],
            options={
                'db_table': 'book',
            },
        ),
        migrations.CreateModel(
            name='Gl_accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoded_key', models.CharField(max_length=255)),
                ('glCode', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Journal_Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('debit_glaccount', models.CharField(max_length=32)),
                ('debit_branch', models.CharField(max_length=255)),
                ('credit_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('credit_glaccount', models.CharField(max_length=32)),
                ('credit_branch', models.CharField(max_length=255)),
                ('notes', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='premier_log_refined',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Account_id', models.CharField(blank=True, max_length=32, null=True)),
                ('client', models.CharField(blank=True, max_length=32, null=True)),
                ('type', models.CharField(blank=True, max_length=32, null=True)),
                ('status', models.CharField(max_length=8)),
                ('status_date', models.DateField(blank=True, null=True)),
                ('date_generated', models.DateField(blank=True, max_length=32, null=True)),
            ],
        ),
    ]
