# Generated by Django 2.0 on 2018-08-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal_entry',
            name='entry_date',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
