# Generated by Django 2.0 on 2018-08-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0003_auto_20180816_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal_entry',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
