# Generated by Django 2.0 on 2018-08-16 13:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0005_auto_20180816_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal_entry',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
