# Generated by Django 2.0 on 2018-08-17 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0007_auto_20180816_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modal_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approve', models.BooleanField()),
                ('reject', models.BooleanField()),
                ('details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demands.Journal_Entry')),
            ],
        ),
    ]
