# Generated by Django 2.0 on 2018-08-17 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0008_modal_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approve_Rejection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entryDate', models.DateField(max_length=20, null=True)),
                ('user', models.CharField(max_length=20, null=True)),
                ('debit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('branch', models.CharField(max_length=255)),
                ('approve_reject', models.CharField(max_length=255)),
                ('notes', models.CharField(max_length=255)),
                ('approved_by', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='modal_details',
            name='details',
        ),
        migrations.AlterField(
            model_name='journal_entry',
            name='entry_date',
            field=models.DateField(max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Modal_Details',
        ),
    ]
