# Generated by Django 2.0 on 2018-08-17 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0009_auto_20180818_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='approve_rejection',
            name='journal_id',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
