# Generated by Django 2.0 on 2018-08-20 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0012_auto_20180818_0027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approve_rejection',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='approve_rejection',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='approve_rejection',
            name='credit',
        ),
        migrations.RemoveField(
            model_name='approve_rejection',
            name='debit',
        ),
        migrations.RemoveField(
            model_name='approve_rejection',
            name='entryDate',
        ),
        migrations.RemoveField(
            model_name='approve_rejection',
            name='journal_id',
        ),
        migrations.RemoveField(
            model_name='approve_rejection',
            name='user',
        ),
        migrations.AddField(
            model_name='approve_rejection',
            name='details',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='demands.Journal_Entry'),
        ),
    ]
