# Generated by Django 2.0 on 2018-08-22 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0013_auto_20180820_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approve_Rejection1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
