# Generated by Django 2.0 on 2018-08-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0014_approve_rejection1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approve_Reject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approve_reject', models.CharField(max_length=20)),
                ('reasons', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='approve_rejection',
            name='details',
        ),
        migrations.DeleteModel(
            name='Approve_Rejection1',
        ),
        migrations.DeleteModel(
            name='Approve_Rejection',
        ),
    ]
