# Generated by Django 2.0 on 2018-08-27 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0016_journal_entry_reasons'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journal_entry',
            options={'ordering': ['-created_at']},
        ),
    ]
