# Generated by Django 2.0 on 2018-08-30 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0017_auto_20180827_1456'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journal_entry',
            options={},
        ),
        migrations.AddField(
            model_name='journal_entry',
            name='credit_gl_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
