# Generated by Django 2.0 on 2018-08-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0018_auto_20180830_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal_entry',
            name='debit_gl_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
