# Generated by Django 2.0 on 2018-08-30 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0019_journal_entry_debit_gl_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal_entry',
            name='credit_gl_name',
        ),
        migrations.RemoveField(
            model_name='journal_entry',
            name='debit_gl_name',
        ),
    ]
