# Generated by Django 2.0 on 2018-08-30 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0020_auto_20180830_2008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journal_entry',
            old_name='debit_glaccount',
            new_name='debitglaccount',
        ),
    ]
